export const Types = {
  SUCCESS_LOGIN: "SUCCESS_LOGIN",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT_USER: "LOGOUT",
  REQUEST_LOGIN: "rEQUEST_LOGIN",
  OPEN_LOGIN_FORM: "OPEN_LOGIN_FORM",
  CLOSE_LOGIN_FORM: "CLOSE_LOGIN_FORM",
};
