export const Types = {
  GET_PRODUCTS: "GET_PRODUCTS",
  INITIAL_PRODUCT_VALUES: "INITIAL_PRODUCT_VALUES",
  ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  GET_SINGLE_PRODUCT: "GET_SINGLE_PRODUCT",
};
