export const Types = {
  SHOPPING_LIST: "SHOPPING_LIST",
  ADD_PRODUCT_TO_LIST: "ADD_PRODUCT_TO_LIST",
  INCREMENT_PRODUCT_IN_LIST: "INCREMENT_PRODUCT_IN_LIST",
  DECREMENT_PRODUCTS_IN_LIST: "DECREMENT_PRODUCTS_IN_LIST",
  DELETE_PRODUCT_FROM_LIST: "DELETE_PRODUCT_FROM_LIST",
};
